import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/navBar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "App Money",
  description: "Generated by create next app",
};

// هذه الدالة الآن سيتم تنفيذها في الخادم باستخدام Server Component
export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mt-20 `}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
