import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/navBar/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "App Money",
  description: "Generated by create next app",
};

// هذه الدالة الآن سيتم تنفيذها في الخادم باستخدام Server Component
export default function RootLayout({ children }) {
  return (
    <html className="dark" lang="en">
      <body className="bg-white  text-black dark:bg-gray-900 dark:text-white mt-20">
        <NavBar />
        {children}
      </body>
    </html>
  );
}

